productline(Features, Attributes):-

Features = [Vehicle, Vehicle_Car, Vehicle_Car_Family, Vehicle_Car_Family_Ford, Vehicle_Car_Family_Citroen, Vehicle_Car_Sports, Vehicle_Car_Sports_Porsche, Vehicle_Car_Sports_Ferrari, Vehicle_Truck, Vehicle_Truck_National, Vehicle_Truck_National_Ford, Vehicle_Truck_National_Renault, Vehicle_Truck_International, Vehicle_Truck_International_Volvo, Vehicle_Truck_International_Mercedes, Vehicle_Bus, Vehicle_Bus_Volkswagen, Vehicle_Bus_Mercedes],

Attributes = [Vehicle_weight, Vehicle_price, Vehicle_Car_weight, Vehicle_Car_price, Vehicle_Car_Family_weight, Vehicle_Car_Family_price, Vehicle_Car_Family_Ford_weight, Vehicle_Car_Family_Ford_price, Vehicle_Car_Family_Citroen_weight, Vehicle_Car_Family_Citroen_price, Vehicle_Car_Sports_weight, Vehicle_Car_Sports_price, Vehicle_Car_Sports_Porsche_weight, Vehicle_Car_Sports_Porsche_price, Vehicle_Car_Sports_Ferrari_weight, Vehicle_Car_Sports_Ferrari_price, Vehicle_Truck_weight, Vehicle_Truck_price, Vehicle_Truck_National_weight, Vehicle_Truck_National_price, Vehicle_Truck_National_Ford_weight, Vehicle_Truck_National_Ford_price, Vehicle_Truck_National_Renault_weight, Vehicle_Truck_National_Renault_price, Vehicle_Truck_International_weight, Vehicle_Truck_International_price, Vehicle_Truck_International_Volvo_weight, Vehicle_Truck_International_Volvo_price, Vehicle_Truck_International_Mercedes_weight, Vehicle_Truck_International_Mercedes_price, Vehicle_Bus_weight, Vehicle_Bus_price, Vehicle_Bus_Volkswagen_weight, Vehicle_Bus_Volkswagen_price, Vehicle_Bus_Mercedes_weight, Vehicle_Bus_Mercedes_price],

fd_domain([Vehicle, Vehicle_Car, Vehicle_Car_Family, Vehicle_Car_Family_Ford, Vehicle_Car_Family_Citroen, Vehicle_Car_Sports, Vehicle_Car_Sports_Porsche, Vehicle_Car_Sports_Ferrari, Vehicle_Truck, Vehicle_Truck_National, Vehicle_Truck_National_Ford, Vehicle_Truck_National_Renault, Vehicle_Truck_International, Vehicle_Truck_International_Volvo, Vehicle_Truck_International_Mercedes, Vehicle_Bus, Vehicle_Bus_Volkswagen, Vehicle_Bus_Mercedes], 0, 1),

Vehicle #> 0 #<=> Vehicle_price #> 0,
Vehicle #> 0 #<=> Vehicle_weight #> 0,
Vehicle_Car #> 0 #<=> Vehicle_Car_price #> 0,
Vehicle_Car #> 0 #<=> Vehicle_Car_weight #> 0,
Vehicle_Car_Family #> 0 #<=> Vehicle_Car_Family_price #> 0,
Vehicle_Car_Family #> 0 #<=> Vehicle_Car_Family_weight #> 0,
Vehicle_Car_Family_Ford #> 0 #<=> Vehicle_Car_Family_Ford_price #> 0,
Vehicle_Car_Family_Ford #> 0 #<=> Vehicle_Car_Family_Ford_weight #> 0,
Vehicle_Car_Family_Citroen #> 0 #<=> Vehicle_Car_Family_Citroen_price #> 0,
Vehicle_Car_Family_Citroen #> 0 #<=> Vehicle_Car_Family_Citroen_weight #> 0,
Vehicle_Car_Sports #> 0 #<=> Vehicle_Car_Sports_price #> 0,
Vehicle_Car_Sports #> 0 #<=> Vehicle_Car_Sports_weight #> 0,
Vehicle_Car_Sports_Porsche #> 0 #<=> Vehicle_Car_Sports_Porsche_price #> 0,
Vehicle_Car_Sports_Porsche #> 0 #<=> Vehicle_Car_Sports_Porsche_weight #> 0,
Vehicle_Car_Sports_Ferrari #> 0 #<=> Vehicle_Car_Sports_Ferrari_price #> 0,
Vehicle_Car_Sports_Ferrari #> 0 #<=> Vehicle_Car_Sports_Ferrari_weight #> 0,
Vehicle_Truck #> 0 #<=> Vehicle_Truck_price #> 0,
Vehicle_Truck #> 0 #<=> Vehicle_Truck_weight #> 0,
Vehicle_Truck_National #> 0 #<=> Vehicle_Truck_National_price #> 0,
Vehicle_Truck_National #> 0 #<=> Vehicle_Truck_National_weight #> 0,
Vehicle_Truck_National_Ford #> 0 #<=> Vehicle_Truck_National_Ford_price #> 0,
Vehicle_Truck_National_Ford #> 0 #<=> Vehicle_Truck_National_Ford_weight #> 0,
Vehicle_Truck_National_Renault #> 0 #<=> Vehicle_Truck_National_Renault_price #> 0,
Vehicle_Truck_National_Renault #> 0 #<=> Vehicle_Truck_National_Renault_weight #> 0,
Vehicle_Truck_International #> 0 #<=> Vehicle_Truck_International_price #> 0,
Vehicle_Truck_International #> 0 #<=> Vehicle_Truck_International_weight #> 0,
Vehicle_Truck_International_Volvo #> 0 #<=> Vehicle_Truck_International_Volvo_price #> 0,
Vehicle_Truck_International_Volvo #> 0 #<=> Vehicle_Truck_International_Volvo_weight #> 0,
Vehicle_Truck_International_Mercedes #> 0 #<=> Vehicle_Truck_International_Mercedes_price #> 0,
Vehicle_Truck_International_Mercedes #> 0 #<=> Vehicle_Truck_International_Mercedes_weight #> 0,
Vehicle_Bus #> 0 #<=> Vehicle_Bus_price #> 0,
Vehicle_Bus #> 0 #<=> Vehicle_Bus_weight #> 0,
Vehicle_Bus_Volkswagen #> 0 #<=> Vehicle_Bus_Volkswagen_price #> 0,
Vehicle_Bus_Volkswagen #> 0 #<=> Vehicle_Bus_Volkswagen_weight #> 0,
Vehicle_Bus_Mercedes #> 0 #<=> Vehicle_Bus_Mercedes_price #> 0,
Vehicle_Bus_Mercedes #> 0 #<=> Vehicle_Bus_Mercedes_weight #> 0,

Vehicle #= 1,
Vehicle_Car + Vehicle_Truck + Vehicle_Bus #= 1,
Vehicle_Car_Family + Vehicle_Car_Sports #= 1,
Vehicle_Car_Family_Ford + Vehicle_Car_Family_Citroen #= 1,
Vehicle_Car_Sports_Porsche + Vehicle_Car_Sports_Ferrari #= 1,
Vehicle_Truck_National + Vehicle_Truck_International #= 1,
Vehicle_Truck_National_Ford + Vehicle_Truck_National_Renault #= 1,
Vehicle_Truck_International_Volvo + Vehicle_Truck_International_Mercedes #= 1,
Vehicle_Bus_Volkswagen + Vehicle_Bus_Mercedes #= 1,

Vehicle_weight #> 0 #==> Vehicle_weight #= R1 + R2 + R3,
Vehicle_Bus #==> R1 #= Vehicle_Bus_weight, #\ Vehicle_Bus #==> R1 #= 0,
Vehicle_Truck #==> R2 #= Vehicle_Truck_weight, #\ Vehicle_Truck #==> R2 #= 0,
Vehicle_Car #==> R3 #= Vehicle_Car_weight, #\ Vehicle_Car #==> R3 #= 0,
Vehicle_price #> 0 #==> Vehicle_price #= R4 + R5 + R6,
Vehicle_Bus #==> R4 #= Vehicle_Bus_price, #\ Vehicle_Bus #==> R4 #= 0,
Vehicle_Truck #==> R5 #= Vehicle_Truck_price, #\ Vehicle_Truck #==> R5 #= 0,
Vehicle_Car #==> R6 #= Vehicle_Car_price, #\ Vehicle_Car #==> R6 #= 0,
Vehicle_Bus_weight #> 0 #==> Vehicle_Bus_weight #= R7 + R8,
Vehicle_Bus_Mercedes #==> R7 #= Vehicle_Bus_Mercedes_weight, #\ Vehicle_Bus_Mercedes #==> R7 #= 0,
Vehicle_Bus_Volkswagen #==> R8 #= Vehicle_Bus_Volkswagen_weight, #\ Vehicle_Bus_Volkswagen #==> R8 #= 0,
Vehicle_Bus_price #> 0 #==> Vehicle_Bus_price #= R9 + R10,
Vehicle_Bus_Mercedes #==> R9 #= Vehicle_Bus_Mercedes_price, #\ Vehicle_Bus_Mercedes #==> R9 #= 0,
Vehicle_Bus_Volkswagen #==> R10 #= Vehicle_Bus_Volkswagen_price, #\ Vehicle_Bus_Volkswagen #==> R10 #= 0,
Vehicle_Bus_Mercedes_weight #> 0 #==> Vehicle_Bus_Mercedes_weight #= 75,
Vehicle_Bus_Mercedes_price #> 0 #==> Vehicle_Bus_Mercedes_price #= 170000,
Vehicle_Bus_Volkswagen_weight #> 0 #==> Vehicle_Bus_Volkswagen_weight #= 8,
Vehicle_Bus_Volkswagen_price #> 0 #==> Vehicle_Bus_Volkswagen_price #= 180000,
Vehicle_Truck_weight #> 0 #==> Vehicle_Truck_weight #= R11 + R12,
Vehicle_Truck_International #==> R11 #= Vehicle_Truck_International_weight, #\ Vehicle_Truck_International #==> R11 #= 0,
Vehicle_Truck_National #==> R12 #= Vehicle_Truck_National_weight, #\ Vehicle_Truck_National #==> R12 #= 0,
Vehicle_Truck_price #> 0 #==> Vehicle_Truck_price #= R13 + R14,
Vehicle_Truck_International #==> R13 #= Vehicle_Truck_International_price, #\ Vehicle_Truck_International #==> R13 #= 0,
Vehicle_Truck_National #==> R14 #= Vehicle_Truck_National_price, #\ Vehicle_Truck_National #==> R14 #= 0,
Vehicle_Truck_International_weight #> 0 #==> Vehicle_Truck_International_weight #= R15 + R16,
Vehicle_Truck_International_Mercedes #==> R15 #= Vehicle_Truck_International_Mercedes_weight, #\ Vehicle_Truck_International_Mercedes #==> R15 #= 0,
Vehicle_Truck_International_Volvo #==> R16 #= Vehicle_Truck_International_Volvo_weight, #\ Vehicle_Truck_International_Volvo #==> R16 #= 0,
Vehicle_Truck_International_price #> 0 #==> Vehicle_Truck_International_price #= R17 + R18,
Vehicle_Truck_International_Mercedes #==> R17 #= Vehicle_Truck_International_Mercedes_price, #\ Vehicle_Truck_International_Mercedes #==> R17 #= 0,
Vehicle_Truck_International_Volvo #==> R18 #= Vehicle_Truck_International_Volvo_price, #\ Vehicle_Truck_International_Volvo #==> R18 #= 0,
Vehicle_Truck_International_Mercedes_weight #> 0 #==> Vehicle_Truck_International_Mercedes_weight #= 135,
Vehicle_Truck_International_Mercedes_price #> 0 #==> Vehicle_Truck_International_Mercedes_price #= 215000,
Vehicle_Truck_International_Volvo_weight #> 0 #==> Vehicle_Truck_International_Volvo_weight #= 10,
Vehicle_Truck_International_Volvo_price #> 0 #==> Vehicle_Truck_International_Volvo_price #= 195000,
Vehicle_Truck_National #==> Vehicle_Truck_National_Renault_price #> 0 #==> Vehicle_Truck_National_Renault_price #= 125000,
Vehicle_Truck_National_price #> 0 #==> Vehicle_Truck_National_price #= 125,
Vehicle_Truck_National_Renault_weight #> 0 #==> Vehicle_Truck_National_Renault_weight #= 5,
Vehicle_Truck_National_Renault_price #> 0 #==> Vehicle_Truck_National_Renault_price #= 125000,
Vehicle_Truck_National_Ford_weight #> 0 #==> Vehicle_Truck_National_Ford_weight #= 45,
Vehicle_Truck_National_Ford_price #> 0 #==> Vehicle_Truck_National_Ford_price #= 122000,
#\ Vehicle_Car_Family_Ford #\/ #\ Vehicle_Car_Sports_Porsche,
Vehicle_Car_Family_Ford #==> Vehicle_Car_Sports_Porsche,
Vehicle_Car_Family_Ford + Vehicle_Car_Sports_Ferrari #=< 1,
Vehicle_Car_weight #> 0 #==> Vehicle_Car_weight #= R19 + R20,
Vehicle_Car_Sports #==> R19 #= Vehicle_Car_Sports_weight, #\ Vehicle_Car_Sports #==> R19 #= 0,
Vehicle_Car_Family #==> R20 #= Vehicle_Car_Family_weight, #\ Vehicle_Car_Family #==> R20 #= 0,
Vehicle_Car_price #> 0 #==> Vehicle_Car_price #= R21 + R22,
Vehicle_Car_Sports #==> R21 #= Vehicle_Car_Sports_price, #\ Vehicle_Car_Sports #==> R21 #= 0,
Vehicle_Car_Family #==> R22 #= Vehicle_Car_Family_price, #\ Vehicle_Car_Family #==> R22 #= 0,
Vehicle_Car_Sports_weight #> 0 #==> Vehicle_Car_Sports_weight #= R23 + R24,
Vehicle_Car_Sports_Ferrari #==> R23 #= Vehicle_Car_Sports_Ferrari_weight, #\ Vehicle_Car_Sports_Ferrari #==> R23 #= 0,
Vehicle_Car_Sports_Porsche #==> R24 #= Vehicle_Car_Sports_Porsche_weight, #\ Vehicle_Car_Sports_Porsche #==> R24 #= 0,
Vehicle_Car_Sports_price #> 0 #==> Vehicle_Car_Sports_price #= R25 + R26,
Vehicle_Car_Sports_Ferrari #==> R25 #= Vehicle_Car_Sports_Ferrari_price, #\ Vehicle_Car_Sports_Ferrari #==> R25 #= 0,
Vehicle_Car_Sports_Porsche #==> R26 #= Vehicle_Car_Sports_Porsche_price, #\ Vehicle_Car_Sports_Porsche #==> R26 #= 0,
Vehicle_Car_Sports_Ferrari_weight #> 0 #==> Vehicle_Car_Sports_Ferrari_weight #= 15,
Vehicle_Car_Sports_Ferrari_price #> 0 #==> Vehicle_Car_Sports_Ferrari_price #= 150000,
Vehicle_Car_Sports_Porsche_weight #> 0 #==> Vehicle_Car_Sports_Porsche_weight #= 8,
Vehicle_Car_Sports_Porsche_price #> 0 #==> Vehicle_Car_Sports_Porsche_price #= 160000,
Vehicle_Car_Family_weight #> 0 #==> Vehicle_Car_Family_weight #= R27 + R28,
Vehicle_Car_Family_Citroen #==> R27 #= Vehicle_Car_Family_Citroen_weight, #\ Vehicle_Car_Family_Citroen #==> R27 #= 0,
Vehicle_Car_Family_Ford #==> R28 #= Vehicle_Car_Family_Ford_weight, #\ Vehicle_Car_Family_Ford #==> R28 #= 0,
Vehicle_Car_Family_price #> 0 #==> Vehicle_Car_Family_price #= R29 + R30 + R31,
R29 #= 60,
R30 #= 80,
R31 #= 13,
Vehicle_Car_Family_Citroen_weight #> 0 #==> Vehicle_Car_Family_Citroen_weight #= 35,
Vehicle_Car_Family_Citroen_price #> 0 #==> Vehicle_Car_Family_Citroen_price #= 22500,
Vehicle_Car_Family_Ford_weight #> 0 #==> Vehicle_Car_Family_Ford_weight #= 3,
Vehicle_Car_Family_Ford_price #> 0 #==> Vehicle_Car_Family_Ford_price #= 25000,

append(Features, Attributes, S),
fd_labeling(S).

